#!/usr/bin/env python3
"""Copy Insightist skills into the flat folder layout that AI tools scan.

The repo stores skills two levels deep (skills/<category>/<skill>/SKILL.md) so they
stay grouped by occupation. Most tools only look one level deep
(<skills-dir>/<skill>/SKILL.md), so this script flattens them on copy.

Standard library only; works on Windows, macOS and Linux.

Examples:
  python3 scripts/install.py --list
  python3 scripts/install.py --target .agents/skills
  python3 scripts/install.py --target ~/.agents/skills --category managers --category professionals
  python3 scripts/install.py --target .workshop/skills --skill okr-goal-setter
  python3 scripts/install.py --target ~/my-project/.agents/skills --agents-md ~/my-project/AGENTS.md
  python3 scripts/install.py --target .agents/skills --force --dry-run

--target is relative to the directory you run the command from (not the repo).
"""
import argparse
import os
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build import CATEGORY_LABELS, discover_skills, render_agents_md, use_utf8_console  # noqa: E402


def parse_args(argv):
    p = argparse.ArgumentParser(
        description="Install Insightist skills into a flat <target>/<skill>/SKILL.md layout.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__.split("Examples:", 1)[1],
    )
    p.add_argument("--target", help="destination skills folder, e.g. .agents/skills or ~/.agents/skills")
    p.add_argument("--category", action="append", default=[], help="only this category folder (repeatable)")
    p.add_argument("--skill", action="append", default=[], help="only this skill id (repeatable)")
    p.add_argument("--force", action="store_true", help="overwrite skills that already exist in the target")
    p.add_argument("--dry-run", action="store_true", help="show what would happen without copying")
    p.add_argument("--list", action="store_true", help="list available categories and skills, then exit")
    p.add_argument(
        "--agents-md",
        metavar="PATH",
        help="also write an AGENTS.md skill index at PATH that points at the installed copies",
    )
    return p.parse_args(argv)


def main(argv=None) -> int:
    use_utf8_console()
    args = parse_args(sys.argv[1:] if argv is None else argv)
    skills = discover_skills()

    if args.list:
        current = None
        for s in skills:
            if s["category"] != current:
                current = s["category"]
                print(f"\n{current}  —  {CATEGORY_LABELS.get(current, '')}")
            print(f"  {s['id']}")
        print(f"\n{len(skills)} skills.")
        return 0

    if not args.target:
        print("error: --target is required (or use --list)", file=sys.stderr)
        return 2

    unknown_cats = set(args.category) - {s["category"] for s in skills}
    unknown_skills = set(args.skill) - {s["id"] for s in skills}
    if unknown_cats or unknown_skills:
        for c in sorted(unknown_cats):
            print(f"error: unknown category '{c}' (see --list)", file=sys.stderr)
        for s in sorted(unknown_skills):
            print(f"error: unknown skill '{s}' (see --list)", file=sys.stderr)
        return 2

    selected = [
        s for s in skills
        if (not args.category or s["category"] in args.category)
        and (not args.skill or s["id"] in args.skill)
    ]
    target = Path(os.path.expanduser(args.target)).resolve()
    prefix = "[dry-run] " if args.dry_run else ""

    installed, skipped = [], []
    for s in selected:
        dest = target / s["id"]
        if dest.exists() and not args.force:
            skipped.append(s)
            print(f"{prefix}skip     {dest}  (exists; use --force to overwrite)")
            continue
        print(f"{prefix}install  {dest}")
        if not args.dry_run:
            if dest.exists():
                shutil.rmtree(dest)
            shutil.copytree(s["dir"], dest)
        installed.append(s)

    if args.agents_md:
        md_path = Path(os.path.expanduser(args.agents_md)).resolve()
        indexed = installed + skipped
        try:
            prefix_path = os.path.relpath(target, md_path.parent)
        except ValueError:  # different drives on Windows
            prefix_path = str(target)
        prefix_path = Path(prefix_path).as_posix().rstrip("/") + "/"
        body = render_agents_md(
            indexed,
            path_prefix=prefix_path,
            source_note=f"Skill folders are installed under `{prefix_path}` (relative to this file).",
        )
        print(f"{prefix}write    {md_path}")
        if not args.dry_run:
            if md_path.exists() and "Generated by scripts/build.py" not in md_path.read_text(encoding="utf-8"):
                print(
                    f"error: {md_path} already exists and was not generated by this script; "
                    "refusing to overwrite. Pick another path or merge by hand.",
                    file=sys.stderr,
                )
                return 1
            md_path.parent.mkdir(parents=True, exist_ok=True)
            md_path.write_text(body, encoding="utf-8")

    print(f"\n{prefix}{len(installed)} installed, {len(skipped)} skipped → {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
